type: "ncp_single_step"
ncp_single_step:
  _target_: models.NcpConfigSingleStep
  ncp_units: 8704  # 256 * 17 * 2
  embed_dim: 256  # Must be less than ncp_units * 17 - 2
  embed_pdrop: 0.1
  blocks_pdrop: 0.1
  num_layers: 1
  ncp_layer_norm: True
  max_blocks: ${common.sequence_length}  # TODO WTF this means?
  tokens_per_block: 17                   # So the Embedder knows. 16 obs + 1 action
